set -g default-terminal "screen-256color"
set -as terminal-features ",*:RGB"
set -s escape-time 10
set -g history-limit 100000
set -g mouse on
set -g focus-events on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
set -g status-position bottom
set -g status-style "fg=#c6d0f5,bg=#303446"
set -g message-style "fg=#232634,bg=#ca9ee6"
set -g pane-border-style "fg=#626880"
set -g pane-active-border-style "fg=#8caaee"
set -g status-left "#[fg=#232634,bg=#8caaee,bold] #S #[default]"
set -g status-right "#[fg=#a5adce]#(whoami)@#H #[fg=#e5c890]%Y-%m-%d %H:%M "
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
